"""Export frozen LUTs to c_port/luts.h (deliberate act only).

Self-contained: builds every table straight from its formula (same
formulas the Python loaders use), so no cache state or model is needed.
Regenerate: python3 scripts/export_luts.py. Diff reviewed, checked in.
Formulas mirror phi_core.L_FRAC/L_COARSE/L_FINE and
rife_int.sig_lut/sigx_lut (gated bit-identical by construction: same
numpy expressions over the same ranges).
"""
import math
import os
import numpy as np

PHI = (1 + math.sqrt(5)) / 2
LN_PHI = math.log(PHI)
K, BIAS = 512, 32768
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "c_core", "luts.h")


def emit(fh, name, arr):
    assert arr.dtype == np.int64, (name, arr.dtype)
    fh.write(f"static const int64_t {name}[{arr.size}] = {{\n")
    for i in range(0, arr.size, 8):
        fh.write(",".join(str(int(v)) for v in arr[i:i + 8]) + ",\n")
    fh.write("};\n")


def main():
    tables = {
        "FRAC": np.round(np.power(PHI, -np.arange(13313) / K) * 2 ** 18).astype(np.int64),
        "COARSE": np.round(np.arange(-64, 129) * K * math.log(2) / LN_PHI).astype(np.int64),
        "FINE": None,  # needs fine_lut lambda — see below
        "SIG": None,
        "SIGX": None,
    }
    # FINE mirrors phi_core.L_FINE exactly:
    tables["FINE"] = np.round(
        K * np.log((16384 + np.arange(16384)) / 16384) / LN_PHI).astype(np.int64)
    k = np.arange(2 * 16 * 16384 + 1, dtype=np.float64)
    tables["SIG"] = np.round(
        1.0 / (1.0 + np.exp(-((k - 16 * 16384) / 16384.0))) * 16384).astype(np.int64)
    tables["SIGX"] = np.round(np.power(
        PHI, (np.arange(65536, dtype=np.float64) - BIAS) / K) * 16384).astype(np.int64)
    with open(OUT, "w") as fh:
        fh.write("/* FROZEN — generated by scripts/export_luts.py. DO NOT EDIT. */\n")
        fh.write("#pragma once\n#include <stdint.h>\n")
        for name, arr in tables.items():
            emit(fh, "LUT_" + name, arr)
            print(name, arr.shape)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
